simplemooc/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login as authLogin
from simplemooc.accounts.views import register

urlpatterns = [
    url(r'^$', authLogin, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^cadastrar/', register, name='register'),
     
]

simplemooc/core/urls.py
from django.conf.urls import url
from simplemooc.core.views import home
from simplemooc.core.views import contato
from simplemooc.core.views import index


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^contato/', contato, name='contato'),
]

simplemooc/courses/urls.py
from django.conf.urls import url
from simplemooc.courses.views import courses
from simplemooc.courses.views import details

urlpatterns = [
	url(r'^$', courses, name='index'),
	url(r'^(?P<slug>[\w_-]+)/$', details, name='details'),

]

simplemooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from simplemooc.core.views import contato
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^contato/', contato, name='contato'),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
from django.db import models

# Create your models here.

simplemooc/core/models.py
from django.db import models

# Create your models here.

simplemooc/courses/models.py
from django.db import models
from django.core.urlresolvers import reverse

class CourseManager(models.Manager):
	def search(self, query):
		return self.get_queryset().filter(
			models.Q(name__icontains=query) | \
			models.Q(description__icontains=query)
		)

class Course(models.Model):
	name = models.CharField('Nome', max_length=100)
	slug = models.SlugField('Atalho')
	description = models.TextField('Descrição', blank=True)
	about = models.TextField('Sobre', blank=True)
	start_date = models.DateField(
		'Data de Inicio', null=True, blank=True
	)
	image = models.ImageField(
		upload_to='courses/images', verbose_name='Imagem',
		null=True, blank=True
	)
	created_at = models.DateTimeField(
		'Criado em', auto_now_add=True
	)
	updated_at = models.DateTimeField(
		'Atualizado em', auto_now=True
	)

	objects = CourseManager()

	def __str__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('courses:details', (), {'slug': self.slug})

	class Meta:
		verbose_name = 'Curso'
		verbose_name_plural = 'Cursos'
		ordering = ['name']

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template


class ContactCourse(forms.Form):

	name = forms.CharField(label = 'Nome', max_length=100)
	email = forms.EmailField(label = 'E-mail')
	message = forms.CharField(
		label = 'Mensagem/Dúvida', widget=forms.Textarea
	)

	def send_mail(self, course):
		subject = 'Contato sobre o Curso %s' % course
		context = {
			'name': self.cleaned_data['name'],
			'email': self.cleaned_data['email'],
			'message' : self.cleaned_data['message'],
		}
		template_name = 'contact_email.html'
		send_mail_template(
			subject, template_name, context, [settings.CONTACT_EMAIL]
		)

simplemooc/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from django.conf import settings

def register(request):
	template_name = 'accounts/register.html'
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect(settings.LOGIN_URL)
	else:
		form = UserCreationForm()
	context = {
		'form': form
	}
	return render(request, template_name, context)

simplemooc/core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse

def index(request):
	return render(request, 'index.html')

def home(request):
	return render(request, 'home.html')

def contato(request):
	return render(request, 'contato.html')

simplemooc/courses/views.py
from django.shortcuts import render

from .models import Course
from .forms import ContactCourse

def courses(request):
	courses = Course.objects.all()
	context = {
		'courses':courses
	}
	return render(request, 'cursos.html', context)

def details(request, slug):
	course = Course.objects.get(slug=slug)
	context = {}
	if request.method == 'POST':
		form = ContactCourse(request.POST)
		if form.is_valid():
			context['is_valid'] = True
			form.send_mail(course)
			form = ContactCourse()
	else:
		form = ContactCourse()
	context['form'] = form
	context['course'] = course
	template_name = 'details.html'
	return render(request, template_name, context)

simplemooc/accounts/templates/accounts/login.html
{% extends "home.html" %}
{% load static %}
{% block header %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-8">
			<div class="page-header" style="position: relative; top: 50px;">
				<h3>Informe os seus dados para efetuar o Login</h3>
			</div>
			<form class="pure-form pure-form-aligned" style="position: relative; top: 50px;" method="post">
			{% csrf_token %}
				<fieldset>
					{{form.non_field_errors}}

					{% for field in form %}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary" style="position: relative;left: 100px;">Entrar</button>
				</fieldset>
			</form>
			<div class="lembrar">
				Não é cadastrado?<a href="">Cadastre-se</a><br>
				Esqueceu a senha?<a href="">Nova Senha</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

simplemooc/accounts/templates/accounts/register.html
{% extends "home.html" %}
{% load static %}
{% block header %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-8">
			<div class="page-header" style="position: relative; top: 50px;">
				<h3>Informe seus dados</h3>
			</div>
			<form class="pure-form pure-form-aligned" style="position: relative; top: 50px;" method="POST">
			{% csrf_token %}
				<fieldset>
					{{form.non_field_errors}}

					{% for field in form %}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary" style="position: relative;left: 100px;">Cadastrar</button>
				</fieldset>
			</form>
		</div>
	</div>
</div>

{% endblock %}

simplemooc/core/templates/contact_email.html
<p>Nome: {{name}}</p>
<p>Email: {{email}}</p>
{{message|linebreaks}}

simplemooc/core/templates/contato.html
{% extends "home.html" %}
{% block header %}
<div class="page-header" id="contato">
	<h3>Contato</h3>
</div>
<div class="container-fluid contato">
	<div class="row">
		<div class="col-sm-12">
			<h3>Para nos contactar siga os endereços a seguir:</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<h2>Email</h2><h4><a href="mailto:jgsorio@allnetgroup.com.br">jgsorio@allnetgroup.com.br</a></h4>
			<h2>Twitter</h2><h4><a href="mailto:jgsorio@allnetgroup.com.br">@joseguilhermesorio</a></h4>
		</div>
	</div>
</div>


{% endblock %}

simplemooc/core/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
	<title>Simplemooc</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
					<span class="sr-only">Navegação</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="{% url 'core:index' %}" class="navbar-brand">SimpleMooc</a>
			</div><!-- ./navbar-header -->

			<div class="collapse navbar-collapse" id="menu">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><a href="{% url 'core:index' %}">Home</a></li>
					<li><a href="{% url 'courses:index' %}">Cursos</a></li>
					<li><a href="{% url 'contato' %}">Contato</a></li>
					<li><a href="{% url 'accounts:login' %}">Logar</a></li>
				</ul>
			</div>
		</div>
	</nav><!-- ./ NAV MENU -->

	{% block header %}{% endblock %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

simplemooc/core/templates/index.html
{% extends "home.html" %}
{% block header %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>

{% endblock %}

simplemooc/courses/templates/cursos.html
{% extends "home.html" %}
{% load static %}
{% block header %}

<div class="container-fluid">
	<h3 id="cursos">Listagem de Cursos Do Simplemooc</h3><br>
	<h4>Abaixo a lista de cursos disponíveis na plataforma</h4>
</div>
<div class="container-fluid">
	{% for course in courses %}
	<div class="row cursos-imagem">
		<div class="col-sm-3">
		{% if course.image %}
			<a href="{% url 'courses:details' course.slug %}">
			<img src="{{course.image.url}}" class="img-responsive">
		{% else %}
			<img src="{% static 'img/img.jpg' %}" class="img-responsive">
		{% endif %}
			</a>
		</div>
		<div class="col-sm-9 descricao">
			<h2>{{course.name}}</h2>
			<h3>{{course.description}}</h3>
		</div>
	</div>
	{% endfor %}
</div>

{% endblock %}

simplemooc/courses/templates/details.html
{% extends "home.html" %}
{% load static %}
{% block header %}

<div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        {{course.name}}
                    </h1>
                    <h2 class="splash-subhead">
                        {{course.description}}
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Inscrever-se</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-8" style="position: relative;top: 50px;">
			{{course.about}}
		</div>
		<div class="col-sm-4" style="position: relative;top: 50px;">
			{% if course.image %}
			<img src="{{course.image.url}}" class="img-responsive">
			{% else %}
			<img src="{% static 'img/img.jpg' %}" class="img-responsive">
			{% endif %}
			<h3>Tire suas duvidas sobre o curso</h3>
			<a href="#contato-curso" class="pure-button">Fale Conosco</a>
		</div>
	</div>
</div>
<div class="container-fluid" id="contato-curso">
	<div class="row">
		<div class="col-sm-4">
		<div class="page-header">
			<h4>Tire as suas dúvidas sobre o Curso</h4>
			{% if is_valid %}
			<div class="alert alert-info" style="position: relative; top: 10px; width: 100%; text-align: center;padding: 2px;">O seu formulário foi enviado com sucesso!</div>
			{% endif %}
		</div>
			<form class="pure-form pure-form-aligned" method="POST">
			{% csrf_token %}
				<fieldset>
					{% for field in form %}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{% if field.errors %}
						<ul class="errorlist">
							{% for error in field.errors %}
							<li>{{error}}</li>
							{% endfor %}
						</ul>
						{% endif %}
					</div>
					{% endfor %}
				</fieldset>

				<div class="pure-controls">
					<button class="pure-button pure-button-primary" type="submit">Enviar</button>
				</div>
			</form><br>
		</div>
	</div>
</div>

{% endblock %}